version: '3.9'

services:
  orchestrator:
    container_name: orchestrator
    build: 
      context: ./orchestrator
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "9090:9090"

  agent:
    container_name: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    volumes:
      - ./agent/config:/app/config

  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05042007PULlup!
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  postgres: