// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: service.proto

package calculatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Arg1          string                 `protobuf:"bytes,2,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2          string                 `protobuf:"bytes,3,opt,name=arg2,proto3" json:"arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationTime *durationpb.Duration   `protobuf:"bytes,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	UserId        uint64                 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetArg1() string {
	if x != nil {
		return x.Arg1
	}
	return ""
}

func (x *Task) GetArg2() string {
	if x != nil {
		return x.Arg2
	}
	return ""
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetOperationTime() *durationpb.Duration {
	if x != nil {
		return x.OperationTime
	}
	return nil
}

func (x *Task) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Result_IntResult
	//	*Result_FloatResult
	//	*Result_Error
	Value         isResult_Value `protobuf_oneof:"value"`
	UserId        uint64         `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Result) GetValue() isResult_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Result) GetIntResult() int64 {
	if x != nil {
		if x, ok := x.Value.(*Result_IntResult); ok {
			return x.IntResult
		}
	}
	return 0
}

func (x *Result) GetFloatResult() float64 {
	if x != nil {
		if x, ok := x.Value.(*Result_FloatResult); ok {
			return x.FloatResult
		}
	}
	return 0
}

func (x *Result) GetError() string {
	if x != nil {
		if x, ok := x.Value.(*Result_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Result) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type isResult_Value interface {
	isResult_Value()
}

type Result_IntResult struct {
	IntResult int64 `protobuf:"varint,2,opt,name=int_result,json=intResult,proto3,oneof"`
}

type Result_FloatResult struct {
	FloatResult float64 `protobuf:"fixed64,3,opt,name=float_result,json=floatResult,proto3,oneof"`
}

type Result_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*Result_IntResult) isResult_Value() {}

func (*Result_FloatResult) isResult_Value() {}

func (*Result_Error) isResult_Value() {}

type ExpressionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expression    string                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionRequest) Reset() {
	*x = ExpressionRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionRequest) ProtoMessage() {}

func (x *ExpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionRequest.ProtoReflect.Descriptor instead.
func (*ExpressionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExpressionRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *ExpressionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExpressionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionResponse) Reset() {
	*x = ExpressionResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionResponse) ProtoMessage() {}

func (x *ExpressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionResponse.ProtoReflect.Descriptor instead.
func (*ExpressionResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExpressionResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResultRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResultResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResultResponse_Value
	//	*ResultResponse_Error
	Result        isResultResponse_Result `protobuf_oneof:"result"`
	Status        string                  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResultResponse) GetResult() isResultResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResultResponse) GetValue() string {
	if x != nil {
		if x, ok := x.Result.(*ResultResponse_Value); ok {
			return x.Value
		}
	}
	return ""
}

func (x *ResultResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ResultResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type isResultResponse_Result interface {
	isResultResponse_Result()
}

type ResultResponse_Value struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3,oneof"`
}

type ResultResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ResultResponse_Value) isResultResponse_Result() {}

func (*ResultResponse_Error) isResultResponse_Result() {}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\rcalculator.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb7\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\tR\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\tR\x04arg2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12@\n" +
	"\x0eoperation_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\roperationTime\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\x04R\x06userId\"\x98\x01\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\n" +
	"int_result\x18\x02 \x01(\x03H\x00R\tintResult\x12#\n" +
	"\ffloat_result\x18\x03 \x01(\x01H\x00R\vfloatResult\x12\x16\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x04R\x06userIdB\a\n" +
	"\x05value\"L\n" +
	"\x11ExpressionRequest\x12\x1e\n" +
	"\n" +
	"expression\x18\x01 \x01(\tR\n" +
	"expression\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"-\n" +
	"\x12ExpressionResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"A\n" +
	"\rResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"b\n" +
	"\x0eResultResponse\x12\x16\n" +
	"\x05value\x18\x01 \x01(\tH\x00R\x05value\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusB\b\n" +
	"\x06result\">\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x8a\x01\n" +
	"\x13OrchestratorService\x126\n" +
	"\aGetTask\x12\x16.google.protobuf.Empty\x1a\x13.calculator.v1.Task\x12;\n" +
	"\n" +
	"SendResult\x12\x15.calculator.v1.Result\x1a\x16.google.protobuf.Empty2T\n" +
	"\fAgentService\x12D\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1d.calculator.v1.HealthResponseB0Z.github.com/yourproject/pkg/api/v1;calculatorv1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_proto_goTypes = []any{
	(*Task)(nil),                // 0: calculator.v1.Task
	(*Result)(nil),              // 1: calculator.v1.Result
	(*ExpressionRequest)(nil),   // 2: calculator.v1.ExpressionRequest
	(*ExpressionResponse)(nil),  // 3: calculator.v1.ExpressionResponse
	(*ResultRequest)(nil),       // 4: calculator.v1.ResultRequest
	(*ResultResponse)(nil),      // 5: calculator.v1.ResultResponse
	(*HealthResponse)(nil),      // 6: calculator.v1.HealthResponse
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
	(*emptypb.Empty)(nil),       // 8: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	7, // 0: calculator.v1.Task.operation_time:type_name -> google.protobuf.Duration
	8, // 1: calculator.v1.OrchestratorService.GetTask:input_type -> google.protobuf.Empty
	1, // 2: calculator.v1.OrchestratorService.SendResult:input_type -> calculator.v1.Result
	8, // 3: calculator.v1.AgentService.HealthCheck:input_type -> google.protobuf.Empty
	0, // 4: calculator.v1.OrchestratorService.GetTask:output_type -> calculator.v1.Task
	8, // 5: calculator.v1.OrchestratorService.SendResult:output_type -> google.protobuf.Empty
	6, // 6: calculator.v1.AgentService.HealthCheck:output_type -> calculator.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_service_proto_msgTypes[1].OneofWrappers = []any{
		(*Result_IntResult)(nil),
		(*Result_FloatResult)(nil),
		(*Result_Error)(nil),
	}
	file_service_proto_msgTypes[5].OneofWrappers = []any{
		(*ResultResponse_Value)(nil),
		(*ResultResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
